### ISSUE TITLE
epoch_start

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#100]
[Markku Kojo said](https://mailarchive.ietf.org/arch/msg/tcpm/nd4Af8QRQMDkp_R_9ZQMkI4yGAc):
>_epoch_start_: needs more accurate and consistent definition when the exactly the epoch starts. Is it when congestion event occurs or when TSP sender enters congestion avoidance first time after an congestion event. If it is  different in different scenarios that would be good to present systematically.

**Comment by goelvidhi** [comment]
From the draft,
>>>  _epoch_start_: The time in seconds at which the current congestion
   avoidance stage started.

So, it is when the sender enters the congestion avoidance first.

**Comment by larseggert** [comment]
Markku, OK to close with no action?

**Comment by goelvidhi** [comment]
@markkukojo, could you please let us know?

**Comment by larseggert** [comment]
No word from @markkukojo, closing this. @markkukojo, please reopen if you disagree.

**Comment by markkukojo** [comment]
I made this note to myself in the early phase of reading the draft and it looks like that I was not very clear what seemed to be the problem. The definition of epoch_start in its brevity seems fine. However, now I see that it was more of its relation to _cwnd_start_ what confused me and in particular what the draft says in Sec 4.2: 
"where _cwnd_start_ is the congestion window at the beginning of the
 current congestion avoidance stage.  For example, right after a
 congestion event, _cwnd_start_ is equal to the new cwnd calculated as
 described in Section 4.6."

The latter sentence starting "For example, ..." is confusing and unnecessary. It kind of hints that _cwnd_start_ would have the same value immediately after a congestion event and in the beginning of the congestion avoidance stage that follows. This is true when a TCP sender receives ECE, for example. I have noticed that some people think that cwnd would also have the same value in the beginning of loss recovery (i.e., after 3 DupAcks triggered Fast Retransmit) and after Fast Recovery completes (i.e., when a TCP sender enters congestion avoidance). Maybe it is because this true for TCP Reno loss recovery. However, it often is not the true with NewReno (RFC 6582) and SACK-based loss recovery (RFC 6675).

I'd suggest deleting the sentence: 

"For example, right after a congestion event, _cwnd_start_ is equal to the new cwnd calculated as described in Section 4.6."

because it is unnecessary and more misleading than clarifying.

**Comment by goelvidhi** [comment]
ok, IIUC, this is unrelated to the original issue which talk about proper definition of epoch_start.

I can create a PR to delete this line.

**Comment by larseggert** [comment]
Closing this one in favor of #119.

**Comment by larseggert** [comment]
Sorry, thought #119 was an issue, but's a PR.
