### ISSUE TITLE
(upon receiving) an ACK

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#101]
[Markku Kojo said](https://mailarchive.ietf.org/arch/msg/tcpm/nd4Af8QRQMDkp_R_9ZQMkI4yGAc):
>In many occassions:
>
>"(upon receiving) an ACK" -> "(upon receiving) a new ACK"

**Comment by larseggert** [comment]
Markku, #103 only fixes the one spot where the text said "Upon receiving an ACK". There are **many* more places where we use "an ACK" - which of those do you think need to be changed?

**Comment by markkukojo** [comment]
I didn't pass through all occurrences because this was a generic comment to be precise. So, throughout the document any occurrence of "an/every/each ACK" that is intended to refer only to an ACK that cumulatively acknowledges new data would be good to indicate exactly (to not leave any doubt that the actions must not be taken on arriving dupAcks or window updates).

**Comment by larseggert** [comment]
Please take a look at #110. I think I found all the places now, but maybe there are some where the old phrasing was OK?
