### ISSUE TITLE
Add details about response to ECN marks

### ISSUE THREAD

**Issue by mohittahiliani** [NTAP/rfc8312bis#11]
It would be nice to describe how a CUBIC sender should respond to ECN marks from the receiver. On receiving an ECE mark, the Linux CUBIC enters a CWR state and follows PRR.

More details about this are available in the document:
https://docs.google.com/document/d/1QiDqBo94wKr1eptTFe6xAB0RWWlwYOy8VLOWrpVAie8/edit

**Comment by sangtaeha** [comment]
@mohittahiliani In fact, CUBIC is not different from the other CCs (e.g., NewReno/SACK) in dealing with ECN marks (treating as a congestion event). Responding to ECN is always beneficial for loss-based algorithms. Yes, we can add that.

**Comment by goelvidhi** [comment]
This was discussed during IETF 109 tcpm meeting. I think what @mohittahiliani was referring to was to document CWR and PRR as done in Linux on ECN which is probably not the same reaction as 3 dup ACKs.

I am not sure if we want to document this behavior of Linux on ECN signaling.

**Comment by sangtaeha** [comment]
@goelvidhi @mohittahiliani If so, all standard loss-based TCP CCs in Linux will do the same for ECN. PRR is how Linux reduces its cwnd and different platforms could do differently. By the way, CUBIC treats ECN as a loss event and sets W_max upon receiving ECN-Echo, which may be enough?  See below.

~~~
After a window reduction in response to a congestion event is detected by duplicate ACKs or Explicit Congestion Notification-Echo (ECN-Echo) ACKs [RFC3168], CUBIC registers the congestion window size where it got the congestion event as W_max and performs a multiplicative decrease of congestion window.
~~~

**Comment by goelvidhi** [comment]
I did point out this text to @mohittahiliani during the tcpm meeting.
I agree that we don't have to document the CWR and PRR for CUBIC specifically.

**Comment by tomhenderson** [comment]
I might suggest that Section 4.5 on Multiplicative Decrease include an additional sentence "For both loss and congestion events, the sender MAY employ a fast recovery algorithm to gradually adjust the congestion window to its new reduced value."  I believe that without this, implementers will assume that cwnd must be immediately reduced (also because PRR does not mention any applicability to ECN).

There is also an opportunity to add ECN support to PRR if that RFC is being revised.

**Comment by lisongxu** [comment]
Thanks, @tomhenderson. We will add that.

**Comment by mohittahiliani** [comment]
Thank you all for the discussion!

**Comment by larseggert** [comment]
Would someone volunteer to craft a PR for this?

**Comment by goelvidhi** [comment]
I can work on this one

**Comment by mwelzl** [comment]
This is not the same thing, but it also fits the topic line: reference [KWAF17] in RFC 8312 is an I-D but it is now RFC 8511, and it's not cited for what it really is about in RFC 8312. RFC 8511 proposes that senders should back off less in response to a CE-mark (note, this is in the world of ECT(0) ) than to a packet loss, because the CE-mark not only indicates congestion - it also indicates the presence of an AQM algorithm, which probably keeps the queue relatively short.

We found this to be generally beneficial, some details here:  https://folk.universitetetioslo.no/michawe/research/publications/Networking2017ABE.pdf
and recommend a value of 0.85 for cubic_beta in the RFC, for whoever wants to participate in this experiment.

I'm not saying that Cubic should now change its backoff factor for good, but the experiment should probably be cited as such, and the reference updated - and if one of you implementers would like to try out a value greater than 0.8, such as 0.85 or 0.8, that would of course be extra cool!

**Comment by goelvidhi** [comment]
@mwelzl The mention of [KWAF17] in Section 5.4 is to note the aggressiveness of CUBIC in fast networks leading to more queuing in the network. For the CUBIC draft, I think it would be best to provide a generic recommendation instead of pointing to specific RFCs for congestion window reduction during fast recovery.
