### ISSUE TITLE
"Application-Limited" seems ambiguous

### ISSUE THREAD

**Issue by maolson-msft** [NTAP/rfc8312bis#137]
It seems like usually "app-limited" refers only to the local app, but if the peer's receive window limits the connection's send rate then we have the same problem where CWnd can grow arbitrarily. So, is "app-limited" supposed to also refer to the peer's receive window? If so, then this should probably be spelled out.

**Comment by goelvidhi** [comment]
Thank you @maolson-msft for raising the issue. RFC 7661 defines app limited as,

> Congestion Window Validation (CWV) [RFC2861] introduced the term
   "application-limited period" for the time when the sender sends less
   than is allowed by the congestion or receiver windows.

There is a reference to RFC 7661 when we talk about rate-limited applications. Is that enough?

**Comment by nealcardwell** [comment]
Good point, Matt. I think we should clarify this explicitly:
         https://github.com/NTAP/rfc8312bis/pull/139

As I noted in the pull request commit message:

We should particularly clarify this because the text on this topic
in 7661 is buggy, when it says:

]   "application-limited period" for the time when the sender sends less
]   than is allowed by the congestion or receiver windows.

This RFC 7661 text is buggy because if the receiver window is
smaller than the congestion window, and the sender sends
an amount equal to the receiver window, then the flow is
application-limited (it is limited by the receiver and receiver
advertised window instead of cwnd).

**Comment by maolson-msft** [comment]
Thanks Neal!

I think a few more details about the actual process for classifying whether the connection is "limited" might also be called for here. This is a pretty tricky part of the algorithm to implement without any hints. For example, I was thinking about the possibility of using the expression (InFlight < CWnd) as the classifier. This would correctly handle both the case where the app is posting bytes too slowly and the case where the peer receive window is too small. But then it occurred to me that a pacing algorithm could also cause InFlight to be smaller than CWnd, and we surely don't want to turn off CWnd growth for that case.

So, can we add some more details about how linux implements this part of the algorithm? Like, does it just terminate the ACK handler at the beginning if min(peer rcvwnd, num bytes posted by app) < CWnd? But then there's the case where CWnd is currently the limiting factor but the current ACK would grow CWnd to a value larger than the peer receive window, in which case we'd probably want to just partially grow the CWnd. Etc.

**Comment by maolson-msft** [comment]
"[viz pacing] we surely don't want to turn off CWnd growth for that case"- actually thinking more about it, I'm not sure we wouldn't also want to turn off CWnd growth when a pacer, or a CPU bottleneck, is causing InFlight to be less than CWnd, since the main idea is that increasing CWnd will not increase the send rate.

The other side of the coin is that if inflight frequently lags cwnd for very short periods, pausing cwnd growth in each of those short periods might unnecessarily hamper growth overall.

**Comment by nealcardwell** [comment]
] I think a few more details about the actual process for classifying whether the connection
] is "limited" might also be called for here. This is a pretty tricky part of the algorithm to implement
] without any hints. 

I agree that deciding whether a connection is cwnd-limited or not is subtle, and important to document. However, IMHO it is also: 

(a) its own complex topic that would open a whole new can of worms, and perhaps excessively delay the release of RFC8312

(b) an algorithm and state machine in its own right, with its own state, and independent of the particular CC algorithm, whether it's Reno or CUBIC

(c) because of (a) and (b), probably worth its own separate RFC

(d) if it were its own new RFC, would be in implicit competition with the RFC 7661 that already covers this topic

If the wording change in pull request #139  is deemed insufficient, then perhaps we should just leave this section as-is?

**Comment by maolson-msft** [comment]
Those are good points, I think. #139 is at least an improvement.
