### ISSUE TITLE
Congestion window TCP friendly region after W_max

### ISSUE THREAD

**Issue by goelvidhi** [NTAP/rfc8312bis#2]
The idea of using alpha_aimd as defined below is to ensure that the congestion window growth for Cubic is similar to standard TCP as Cubic's reduction factor (0.3) is smaller than that of standard TCP (0.5)

Currently, alpha_aimd = 3*(1-beta_cubic)/(1+beta_cubic) // for the entire TCP friendly region

But we think that once the cwnd in TF region reaches W_max, we should set the alpha_aimd to 1 to have similar behavior as standard TCP congestion algorithm (eg. NewReno)

if (W_est < W_max)
	alpha_aimd = 3*(1-beta_cubic)/(1+beta_cubic)
else
	alpha_aimd = 1

I'd be happy to work on a PR for this if folks think that this would be a good addition.

**Comment by lisongxu** [comment]
Thank you, you are right that once cwnd reaches W_max, we should set alpha_aimd (or the delta variable in Linux) to 1 to make sure that CUBIC has at least the same throughput as the standard TCP. 

But if the purpose of this RFC is to document the current Linux CUBIC implementation, then we do not need to change it. 

Thanks,

**Comment by larseggert** [comment]
@lisongxu Is this a change that should be committed to Linux?

We should also poll other implementations if they are doing something similar to what is proposed already, or would start doing so if we made the change.

**Comment by goelvidhi** [comment]
Correct if I am wrong, but I think the purpose of an RFC should be to document what would be the right behavior for the algorithm instead of what a particular implementation is doing. Having said that, as Linux is widely used OS, I think it would be good to commit this to Linux if we agree that this is a required change.

@larseggert what is the best way to start a poll for other implementations? A slack channel?

**Comment by larseggert** [comment]
@goelvidhi RFC8312 was specifically written because there was no accurate CUBIC specification at the time other than the Linux source code (the paper algorithm was outdated.) I think we should try and stick to this for the revision, i.e., document the CUBIC variant that is used in production now, in Linux and other stacks.

That said, *if* there are modifications that we want to propose that would further improve CUBIC beyond what current implementations are doing, that is possible. But I'd like to then see if Linux and other stacks would be open to implementing these improvements -- I wouldn't want to end up with a CUBIC spec that is (again) divergent from what the main stacks do (in some aspects).

As for how to ask, I think an email to the TCPM WG mailing list with a pointer to the respective GitHub issue/PR works best.

**Comment by lisongxu** [comment]
I am not sure, but I guess this change has little impact on the cubic performance, especially in highspeed networks.  Thanks

**Comment by maolson-msft** [comment]
I can speak for Windows TCP and MsQuic, and this proposal isn't done in either today.

If you just change the slope but not the base of the linear function, then I think you'll see a jump discontinuity in the window. That's a problem for Windows TCP because we don't pace by default. To avoid the jump discontinuity, you could rebase the linear function:

instead of the proposed
W_est(t) = W_max*BETA + (t/RTT)
[where t = time in congestion avoidance],

you could do
W_est(t) = W_max + t/RTT
[where t = time since W_est hit W_max].

Something like that. But of course, if this isn't going to substantially affect perf in real scenarios, I'd rather not risk the bugs from making this change.

**Comment by goelvidhi** [comment]
@maolson-msft 
The W_est equation is
W_est(t)= W_max*beta_cubic +
                   [3*(1-beta_cubic)/(1+beta_cubic)] * (t/RTT)

where alpha_aimd = 3*(1-beta_cubic)/(1+beta_cubic)

And the suggestion is to set alpha_aimd to 1 after W_est hit W_max for parity with New Reno.

**Comment by maolson-msft** [comment]
@goelvidhi , setting alpha to 1 reduces the RFC's current equation to W_est(t) = W_max*BETA + t/RTT, which is the equation I wrote. Sorry if that was unclear.

**Comment by goelvidhi** [comment]
Hmm, I see your point.
I use bytes_acked/cwnd instead of time t/RTT, so don't have the problem as you described. I need to think more about this issue.

**Comment by maolson-msft** [comment]
@goelvidhi , I agree that issue #20 (replacing the equation-based window to an ACK-clocked one), if accepted, will resolve this jump discontinuity problem.

**Comment by nealcardwell** [comment]
Yuchung Cheng and I chatted about this proposed fix above ( https://github.com/NTAP/rfc8312bis/issues/2#issue-742936185 ) and we agreed this looks like a nice and worthwhile fix, which we should be able to integrate
into the Linux TCP CUBIC implementation.

This should address the concern mentioned above from Lars about potential drift between Linux TCP CUBIC and the RFC ( https://github.com/NTAP/rfc8312bis/issues/2#issuecomment-727789321 ).

**Comment by larseggert** [comment]
Would someone volunteer to craft a PR for this?

**Comment by goelvidhi** [comment]
I can work on this one
