### ISSUE TITLE
Clear definition of "the beginning of the current congestion avoidance stage"

### ISSUE THREAD

**Issue by rscheff** [NTAP/rfc8312bis#21]
While improving the FreeBSD Cubic implementation, we found that there is ambiguity as to when to define "the beginning of the current congestion avoidance stage". However, for the classical design assumption for TCP with infinite data available to send, the minutae don't matter much.

But in a corner case, let us assume the send buffer allows the transmission of exactly ssthresh bytes. After that, the application stalls for some time (in multiples of the RTT) before making more data available to send...

In the original code, t(0) was set, once cwnd > ssthresh (before the application stall above). 

However, that can lead to excessive jumps, when cubic re-calculates cwnd the next time data is available for sending, as an excessive amount of time may have passed.

When FreeBSD is doing now ([https://reviews.freebsd.org/D25746](D25746)) is to track properly, when the first time to recalculate cwnd is after having left ssthresh (or having been application limited, which is similar).

We have not looked closely how app-limited and request/response type flows are handled with cubic in Linux or other OS.

A clear definition as to when to start taking the base t(0) for calculating t in the cubic formular may be good to have.

**Comment by lisongxu** [comment]
Thanks, @rscheff . This is what we are discussing in "[Some bugs to fix #14](https://github.com/NTAP/rfc8312bis/issues/14)".

What Linux does and what the current RFC 8312 specifies is "Section 5.8: CUBIC does not raise its congestion window size if the flow is currently limited by the application instead of the congestion window.  In case of long periods when cwnd has not been updated due  to the application rate limit, such as idle periods, t in Eq. 1 MUST NOT include these periods; otherwise, W_cubic(t) might be very high after restarting from these periods."

**Comment by larseggert** [comment]
Closing this, since the discussion is in #14
