### ISSUE TITLE
Add handling of spurious retransmissions

### ISSUE THREAD

**Issue by huitema** [NTAP/rfc8312bis#23]
I wrote up a blog last year describing [my experience implementing Cubic for QUIC](https://huitema.wordpress.com/2019/11/11/implementing-cubic-congestion-control-in-quic/). There were three points:

1) Issues with the formula base "Reno compatibility", which is documented in issue #20 
2) Sensitivity of Hystart to delay jitter, which is more an issue with Hystart than with Cubic
3) Sensitivity to spurious repeats

I think that third issue should be addressed in the revised RFC. The basic problem is that any detected packet loss causes the host to reduce the window and start a new epoch. In some environments we can see spurious loss detection, caused for example by delayed ACKs or out of order delivery. These spurious losses can be easily identified in QUIC, and with some extra work in TCP. It would be useful if the revised RFC has a section on handling spurious losses.

The handling that I did implement was simple: reset the epoch parameters to the value of the previous epoch, before the loss. Documenting at least that would be nice.

**Comment by nealcardwell** [comment]
Fixing this would be great, since spurious retransmissions (e.g. from reordering) are so common. FWIW, undoing cwnd reductions is not correctly implemented in Linux TCP CUBIC (only cwnd is reverted, not the epoch parameters), but @yuchungcheng has a patch for this that we should be able to incorporate into Linux.

**Comment by goelvidhi** [comment]
This is a good suggestion. Hopefully, it will promote any future congestion controllers draft to include this scenario among others, i.e. aim for completeness.

**Comment by lisongxu** [comment]
Thank you all, yes, I agree that this is a very good suggestion.  

What are some common reasons for spurious retransmissions?   

@nealcardwell you mentioned packet ordering, do you know why it is common (now)? because of more wireless/cellular networks?  

@huitema you mentioned ACK compression in your blog (interesting to read!), could you please explain why ACK compression leads to spurious retransmissions? 

Thank you!

**Comment by nealcardwell** [comment]
@lisongxu the RACK draft has one perspective on some reasons for reordering: https://tools.ietf.org/html/draft-ietf-tcpm-rack-13#section-2.2

   3.  Packet reordering.  Link-layer protocols (e.g., 802.11 block
       ACK), link bonding, or routers' internal load-balancing (e.g.,
       ECMP) can deliver TCP segments out of order.  ...

**Comment by huitema** [comment]
I observed that on some wireless connections (WiFi plus fixed LTE), one of the routers on path was bundling short packets together and only sending them when the bundle had attained a sufficient size. (QUIC ACK are short packets, but they are encrypted and the routers cannot tell them from other short packets.) In my case, the packet bundling process caused extra delays, and sometimes the timers were firing.

As for reordering, that's very common too. @nealcardwell has access to much better telemetry than I do, but one behavior I saw was routers putting short packets in front of the queue, before longer packets. That can confuse algorithms like RACK.

**Comment by lisongxu** [comment]
Thank you, Neal and Christian!

**Comment by larseggert** [comment]
Would someone volunteer to craft a PR for this?

**Comment by goelvidhi** [comment]
I can work on this

**Comment by mwelzl** [comment]
I wonder how "reset the epoch parameters to the value of the previous epoch, before the loss" is different from "only initialize the epoch parameters when a CA epoch begins *normally*, i.e. not after a spurious loss event".

In the latter case, the fix could just be a matter of writing:  "If the loss event preceding this CA epoch was not spurious: "  in front of the text describing how some variables are initialised at the beginning of CA.

**Comment by nealcardwell** [comment]
IMHO it is important to do more than add the text "If the loss event preceding this CA epoch was not spurious: ".

The CUBIC implementation will not know at the time of the loss event whether the loss recovery episode was spurious or not. So for the implementation these are necessarily two different events at different times:

 (a) loss event
 (b) subsequent discovery that the loss recovery episode was spurious

IMHO it is important to document exactly how the algorithm handles both (a) and (b), since there is a specific set of algorithm variables that need to be saved in (a) and then restored in (b). (It would be easy for an implementation to forget to save/store one ore more of the variables.)

**Comment by mwelzl** [comment]
Hm, so maybe "saving" and "restoring" is a kernel implementation specific requirement?

I thought that the "epoch parameters" are things like the cwnd at the time of starting CA and the time when CA begins (to later calculate t), for example. These things can be set exactly when CA begins - and when it does, TCP can (in principle) know how it got there - via a regular termination of, e.g., FR, or via a spurious loss event "undo".

**Comment by nealcardwell** [comment]
It is not the case that TCP will always know when CA begins whether the preceding loss event was spurious or not. For example, DSACKs for spurious retransmits often arrive one round-trip *after* the loss recovery episode completes and the CA episode begins. So if the loss recovery episode is detected as spurious via DSACKs, then usually the sender does not know at the time CA starts that the loss recovery was spurious.

So the implementation needs to be prepared for the events (a) and (b) in my timeline above to be separate events at separate times.

**Comment by mwelzl** [comment]
Ah, sure; I didn't think of that - DSACKs in particular are a good example, thanks.

**Comment by lisongxu** [comment]
@nealcardwell Thank you for your comments! We are working on a section for this issue and plan to refer to some possible methods (e.g., using DSACK) to determine whether a loss event was spurious or not. Are you aware of any related documents or RFCs? Thanks

**Comment by mwelzl** [comment]
I'm not Neal, but still - AFAIK there are three well known methods, which are documented in RFCs: Eifel (RFCs 3522 / 4015, working very well but only if you have timestamps), F-RTO (RFC 5682), working very well and not needing anything extra from the receiver but limited to timeouts, and DSACK (RFC 3708), which is reliable when available, but late.

Various other methods are possible, depending on the transport... quite possibly something reliable could be done with QUIC. I once worked on doing it with the ECN nonce, which noone ever used anyway and which is now even obsolete  :-) https://folk.universitetetioslo.no/michawe/research/projects/spurious/index.html

**Comment by lisongxu** [comment]
Hi @yuchungcheng , @nealcardwell  mentioned that you already have a patch to undo the cwnd reduction of Cubic in case of spurious loss events. In this case, do you think it is better to shift epoch_start as Cubic currently [does for application-limited cases](https://github.com/torvalds/linux/blob/master/net/ipv4/tcp_cubic.c#L149) (i.e., exclude the spurious-loss-related period from K)? Otherwise, Cubic would increase its cwnd too aggressively, especially if the fast recovery period is very long. Thanks

**Comment by lisongxu** [comment]
Thank you so much, @mwelzl ! This is very helpful!

**Comment by nealcardwell** [comment]
Yes, thanks, @mwelzl. That's a nice summary of all the undo mechanisms I'm aware of (and all the undo mechanisms that I can think of in the Linux TCP stack).

**Comment by nealcardwell** [comment]
Re "do you think it is better to shift epoch_start as Cubic currently does for application-limited cases", I think it is much better to restore the epoch_start and related variables (epoch_start, last_max_cwnd, cwnd,...) to the values they had before the spurious loss recovery, so that the sender can quickly get back to the cwnd curve it would have had if there had not been a spurious loss recovery. And this is what the draft patch by @yuchungcheng did.

**Comment by lisongxu** [comment]
Thank you, @nealcardwell ! Just to clarify, there are two possible different methods to restore Cubic, depending on whether we restore cwnd or epoch_start. Considering one example, where the original cwnd was 100 and the original epoch_start was 10 seconds just before the spurious loss.

1) restore to the original cwnd just before the spurious loss.  For the above example, we restore cwnd back to 100 after detecting the spurious loss. But to do so, we need to shift epoch_start accordingly (i.e., plus the time period between when the spurious loss occurred and when it was detected).

2) restore to the original epoch_start. For the above example, we restore epoch_start back to 10 seconds after detecting the spurious loss, but then the new cwnd calculated using the restored original epoch_start would be much higher than the original cwnd 100.  

Among these two methods, it seems that method 1 is safer. 

Thanks

**Comment by huitema** [comment]
About the "other transports": for QUIC, detection of spurious loss detection is very simple because all packets have monotonically increasing sequence numbers. Spurious loss detection happens as follow:

1) At time t, packet number N is marked as lost by standard loss detection, triggering actions like scheduling retransmission of some of the frames carried by the packet and signalling of a packet loss event to the congestion controller.
2) Later, at time t + dt, an acknowledgement is received for the same packet number N. At that point, a "spurious loss detection" event is sent to the congestion controller.

**Comment by huitema** [comment]
For the correction of spurious losses, what I did in my implementation of QUIC was pretty much what @nealcardwell described: restore the epoch start and the associated variables. Only restoring the CWIN leaves the connection in a "half-way" state between erasing the spurious loss and suffering from it, and that's probably a bad idea.

**Comment by yuchungcheng** [comment]
Lisong -- my (drafted) patch does #1. diff attached (it was written a few
years ago so may not apply cleanly)

**Comment by nealcardwell** [comment]
@lisongxu, you mentioned: "there are two possible different methods to restore Cubic, depending on whether we restore cwnd or epoch_start". AFAICT it is better to restore both cwnd and epoch_start (to the values they had immediately before the spurious loss detection event). How does that sound?

You also mentioned: "1. restore to the original cwnd just before the spurious loss. For the above example, we restore cwnd back to 100 after detecting the spurious loss. But to do so, we need to shift epoch_start accordingly (i.e., plus the time period between when the spurious loss occurred and when it was detected)." In this case, why would we need to shift epoch_start? Why not restore epoch_start to the value it had before the spurious loss detection event?

My sense would be that the goal for handling spurious retransmissions should be that, as much as possible, the state of the CUBIC algorithm should be restored so that the behavior of the connection would be as if the spurious retransmissions never happened. This is what Reno does in Linux, and it seems to me that this should be doable for CUBIC as well.

**Comment by lisongxu** [comment]
Thank you all for your comments!

@yuchungcheng  Hi Yuchung, it seems that the diff attachment was blocked somewhere. Could you please directly email it to me at xu@unl.edu? Thank you!

**Comment by lisongxu** [comment]
@nealcardwell Hi Neal, I can see that my original description is not that clear. Below I try to describe the two methods using two figures.

Method 1: undo cwnd and shift epoch_start so that cwnd continues smoothly from the value it had before the spurious loss. 
![cubic](https://user-images.githubusercontent.com/10427041/101723253-86126500-3a71-11eb-84b8-f053775e69e1.jpg)

Method 2:  undo cwnd and undo epoch_start. In this case, there is a big jump from restored cwnd and the next RTT cwnd (calculated using restored epoch_start)
![cubic2](https://user-images.githubusercontent.com/10427041/101723556-1e104e80-3a72-11eb-9118-cf040113ce78.jpg)

Both methods are ok, but method 1 is more conservative and thus possibly safer?

Thanks

**Comment by goelvidhi** [comment]
Thanks @lisongxu for the graphical explanation. IMO, method 2 is better as the cwnd grows in a manner that spurious cwnd reduction never occurred.

OTOH method 1 is conservative and might be safer, but I don't understand how can a transport extrapolate the shifted epoch start? From your graph, if spurious loss occurred at X and spurious loss detection occurred at Y (at which point we reduced cwnd to 100), how does one calculate the time X` (between X and Y) for the epoch start?

**Comment by nealcardwell** [comment]
Thanks @lisongxu for the very nice graphical explanation. I agree with @goelvidhi  and maintain that restoring both cwnd and epoch start to the value before the spurious loss event occurred would be the best approach.

Keeping in mind the typical long time-scales over which the CUBIC curve evolves (for high-BDP connections for which the CUBIC curve is governing behavior, rather than the Reno emulation), and the quick 1-2 round-trip resolution of undo events, my sense is that a depiction that better conveys the sense of Method 2 (restoring both cwnd and epoch start ) would be something like:

![image](https://user-images.githubusercontent.com/11696413/101785344-a3275200-3aca-11eb-941d-9ed7f71b7d55.png)

**Comment by lisongxu** [comment]
Thank you all for the constructive discussions. Then let's choose method 2, which should be easier to implement than method 1. In addition, the revised RFC requires that the per-RTT cwnd increment is limited by that [1.5x upper bound](https://github.com/NTAP/rfc8312bis/issues/14), so method 2 should be fine even in special cases where undo happens many RTTs after a spurious loss event.
