### ISSUE TITLE
Why a_aimd can be set to 1 

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#68]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>> 9: Section 4.3  "Note that once _W_est_ reaches _W_max_, that is, _W_est_ >= _W_max_, ..."
>
>   I might miss something, but I'm not sure why  a_aimd can be set to 1 to be compatible with AIMD TCP.
   Does this mean b_cubic is also updated? If not, why this can be compatible?

**Comment by goelvidhi** [comment]
This is discussed in https://github.com/NTAP/rfc8312bis/issues/2. Note that we have updated the AIMD friendly formula to make it byte based just like New Reno. We have also removed B_cubic. 
<img width="714" alt="Screen Shot 2021-06-03 at 12 44 50 AM" src="https://user-images.githubusercontent.com/10913828/120607311-ebce2100-c404-11eb-8957-0a04008f6d1f.png">

**Comment by larseggert** [comment]
@nsdyoshi does this address your comment?

**Comment by nsdyoshi** [comment]
Sorry.. it's still not clear to me. I'm wondering the following 2 points. 

- It seems to me that W_est has two phases in cwnd increasing. But, I believe this kind of behavior doesn't exist in Reno. I'm not sure why it has to have two phases.
- if setting a_aimd to 1 is compatible with AIMD TCP,  a_aimd = 3 * (1-b_cubic) / (1+b_cubic) is not compatible with AIMD TCP?

**Comment by goelvidhi** [comment]
> It seems to me that W_est has two phases in cwnd increasing. But, I believe this kind of behavior doesn't exist in Reno. I'm not sure why it has to have two phases.

Two phases because after loss, Cubic reduces its congestion window to 0.7x while New Reno reduces it to 0.5x. To have the same increase curve in AIMD friendly region, for Cubic, Alpha_aimd is < 1

>if setting a_aimd to 1 is compatible with AIMD TCP, a_aimd = 3 * (1-b_cubic) / (1+b_cubic) is not compatible with AIMD TCP?
This is again the same reasoning. Before the cwnd reaches W_max, Cubic needs to be more conservative so alpha_aimd = 0.529 instead of 1. After we have reached the previous cwnd, i.e. W_max, Cubic can have the same alpha_aimd (i.e. 1) as New Reno has.

**Comment by nsdyoshi** [comment]
Hmm. I'm not sure about it.

In my understanding, alpha_aimd = 0.529 is chosen because AMID(1, 0.5) =AIMD(0.529, 0.7). 
If you change it to 1, it will be AIMD(1, 0.7) which is more aggressive than AIMD(1, 0.5)

**Comment by lisongxu** [comment]
The throughput model of AIMD(alpha, beta) assumes a deterministic loss model where a packet is lost every time when the cwnd reaches w_max. 

The "a_aimd can be set to 1" is proposed to clearly describe the behavior of CUBIC when cwnd > w_max.

**Comment by goelvidhi** [comment]
I had explained this in the last IETF meeting. Here is the diagram I used. For low BDPs when we use the AIMD friendly equation, alpha_aimd = 0.529 only has meaning until we reach W_max. After that New Reno and Cubic should behave the same.
<img width="939" alt="Screen Shot 2021-06-07 at 7 31 34 PM" src="https://user-images.githubusercontent.com/10913828/121113499-fd2d7980-c7c6-11eb-89a8-a147557c8128.png">

**Comment by nsdyoshi** [comment]
OK. I understand the concept. Thank you so much. But, It seems to me the sentence looks a bit confusing. 
I am thinking about something like the below, but there might be better descriptions for this.

Note that once _W_est_ reaches _W_max_, that is, _W_est_ >= _W_max_,
 α__aimd_ SHOULD be set to 1 because we don't know what new W_max will be at this point.
This ensures CUBIC to achieve the same congestion window increment as AIMD TCP.

**Comment by lisongxu** [comment]
Thank you, Yoshi, for your suggestion!
