### ISSUE TITLE
Overridden by linear growth by AIMD

### ISSUE THREAD

**Issue by larseggert** [NTAP/rfc8312bis#69]
[Yoshi said](https://mailarchive.ietf.org/arch/msg/tcpm/W-t1q8q6Q0Ofjcp0iXOgmY18mr0):
>> 10: Section 4.5: " The convex profile ensure that the window increases very slowly at the beginning.."
>
>   I am wondering how much this part is accurate. Because of Principal 2,  even though cwnd is increased 
   through convex profile, I think it will be overridden by linear growth by AIMD.

**Comment by goelvidhi** [comment]
According to principle 2,
> A congestion control algorithm designed to be friendly to AIMD TCP on
>   a per-flow basis must increase its congestion window less
>  aggressively in small BDP networks than in large BDP networks.

CUBIC uses AIMD friendly equation for small BDPs, which means that it doesn't use the cubic curve in those scenarios.
And AIMD algorithms like New Reno don't scale well in large BDPs.

**Comment by larseggert** [comment]
@nsdyoshi does this address your comment?

**Comment by nsdyoshi** [comment]
Please let me explain a bit more.

From Section 3.2
> Furthermore, in cases when the cubic function of CUBIC would increase
   the congestion window less aggressively than AIMD TCP, CUBIC simply
   follows the window size of AIMD TCP to ensure that CUBIC achieves at
   least the same throughput as AIMD TCP in small-BDP networks. 

From Section 4.3
> CUBIC checks whether W_cubic(_t_)
   is less than _W_est_. If so, CUBIC is in the AIMD-friendly region and
   _cwnd_ SHOULD be set to _W_est_ at each reception of an ACK.

In my understanding,  w_cubic and w_est behave like this (well, this graph is not very precise as W_est will not be a straight line in the draft)
Around W_max, w_cubic's window growth is small as it uses cubic function, but it will be overridden by W_est if we are following the logic described in the draft. This behavior is fine for me, but I think the description: "very slowly" in Section 4.5 is not very accurate because it is the same level as Reno.
Please point out if I overlook something here.

![image](https://user-images.githubusercontent.com/73777040/120773757-7cc0fd00-c4d6-11eb-9d62-357562f740cf.png)

**Comment by goelvidhi** [comment]
I think you are mixing up two different things.

Section 3.2 is talking about AIMD friendliness in Low BDP networks and that has nothing to do with how convex part of Cubic curve starts with a slow increase. That section is about, in low BDP networks, the max. window size attained by Cubic is generally low and that's why after a loss, AIMD like growth would be higher than cubic curve (even for concave).

Section 4.5 is talking about, when cubic is NOT in AIMD friendly region, i.e. cwnd > W_est, and cwnd > W_max, then we use the convex curve. This would happen for high BDP networks. Although the increase would be greater than New Reno but it would be increase slowly around W_max to probe the new peak bandwidth and in most cases, Cubic will incur a loss soon and exit the convex phase.

**Comment by nsdyoshi** [comment]
Hmm. It seems to me that you are explaining Section 4.5 is talking about the right side of the pink line in the figure. 
But, I'm not very sure about it. Because at this point, cwnd is already over W_max, there is no need to be careful from my point of view. 

In this case, I think the following sentences in the section is not applicable. It doesn't look carefully or very slowly to me.

>In this region, CUBIC is very careful.  The convex profile ensures
   that the window increases very slowly at the beginning and gradually
   increases its increase rate.   



![image](https://user-images.githubusercontent.com/73777040/120888219-fc6ccb80-c5ab-11eb-8d34-c7603878f57f.png)

**Comment by lisongxu** [comment]
@nsdyoshi  Thanks, Yoshi! Your figure is kind of misleading in that both the green curve (W_cubic) and orange line (W_est) pass W_max at the same time. In high-speed networks, the orange line increases very slowly and passes W_max much later than the green curve.  I added a new orange line in your figure to illustrate that. 

![120888219-fc6ccb80-c5ab-11eb-8d34-c7603878f57f](https://user-images.githubusercontent.com/10427041/121112213-ba26d280-c7d5-11eb-9bf9-78fafcdfcf11.png)

**Comment by goelvidhi** [comment]
Section 4.5 talks about this scenario - in high BDP networks, the AIMD growth is very slow and it take a lot of RTTs to recover to W_max. So, cubic curve - concave then convex is used where convex would increase slowly around W_max. Something like this:

<img width="754" alt="Screen Shot 2021-06-07 at 7 26 51 PM" src="https://user-images.githubusercontent.com/10913828/121113123-577a0a80-c7c6-11eb-969e-6e9aa4065427.png">

**Comment by goelvidhi** [comment]
Ah, I saw Lisong's comment after I posted. But yes, we are both saying the same thing

**Comment by nsdyoshi** [comment]
Yes, It's true for high BDP network case. But, I was thinking about small BDP network case. It seems to me that Section 4.5 doesn't talk about high BDP cases only. Because, even small BDP network cases will have convex region.

In small BDP case, I think w_est grows lot faster and the beginning of concave region will be overridden by it and convex region will start when cwnd becomes  lots bigger than w_max. 
In this situation, I'm not very sure to say "window increases very slowly at the beginning" 

I am thinking that the explanation something like this might describe the behavior more accurately.

Unless it is not overridden by AIMD window increase, CUBIC is very careful in this region.  
The convex profile aims that the window increases very slowly at the beginning and gradually increases its increase rate.

**Comment by goelvidhi** [comment]
@nsdyoshi I was able to plot the graph you initially posted with some sample values (W_max = 100, cwnd_start = 70, RTT = 75ms).
<img width="711" alt="Screen Shot 2021-06-17 at 12 51 28 AM" src="https://user-images.githubusercontent.com/10913828/122354787-2e642300-cf06-11eb-988e-02f52c307b1c.png">


I will create a PR to add this suggestion.

**Comment by nsdyoshi** [comment]
right. but, when I look at the picture you've shown, the concave region starts at the point where cwnd is way bigger than w_max.
In this case, I'm not sure if the following description of the concave region is accurate. 
I think it would be good if we can provide more explanations here.

> In this region, CUBIC is very careful.  The convex profile ensures
   that the window increases very slowly at the beginning and gradually
   increases its increase rate.

**Comment by lisongxu** [comment]
Thanks, Yoshi.  That "very slowly" is about the behavior of cubic in the convex region, which is defined in Section 4.2 "The concave region, if CUBIC is not in the AIMD-friendly region and cwnd is less than Wmax."

**Comment by nsdyoshi** [comment]
Hmm. sorry. I meant convex region.
I quoted the texts from Section 4.5. So, it should describe the behavior of cubic in the convex region. 
The 'very careful' and 'very slowly' describes the behavior of cubic well when BDP is large. (as shown in the first figure Vidhi put) 
However, I think this description is not very accurate when BDP is small (as shown in the second figure from Vidhi) 
That's why I am thinking it might be good to add some more explanations here.

**Comment by lisongxu** [comment]
Both the 'very careful' and 'very slowly' describe the behavior of the convex/concave regions (that is, the behavior of the blue line).  If the green line is above the blue line, then CUBIC does not enter the convex or concave regions. Hope this helps.

**Comment by nsdyoshi** [comment]
Hi Lisong, 

In my thoughts, convex region starts when cwnd >= w_max and it's not in TCP friendly region. So, I thought the starting point of the convex region is the red dot in the following figure.

![image](https://user-images.githubusercontent.com/73777040/122666467-3ae4b780-d162-11eb-9f5d-48685ecfb58c.png)

But, I am guessing you consider the starting point of the convex region is always cwnd = w_max. But, when cwnd_cubic < w_est, CUBIC is not in the region. (Please correct me if I miss something here)

In my reading of the draft, I think both interpretations are possible. I believe it would be good if we can eliminate ambiguity here.

**Comment by goelvidhi** [comment]
> In my thoughts, convex region starts when cwnd >= w_max and it's not in TCP friendly region.

@nsdyoshi you are right and this is what the draft mentions in Section 4.5

> So, I thought the starting point of the convex region is the red dot in the following figure. 

Cubic is in convex region at this red dot even if the convex profile starts at cwnd = W_max.

Perhaps you are concerned about this line and now I fully understand your concern. Although the intro in Section 4.5 says that Cubic starts at red dot, the below line is a bit contradictory as it probably assumes that Cubic will always be in convex region around W_max.
> In this region, CUBIC is very careful. The convex profile ensures that the window increases very slowly at the beginning and gradually increases its increase rate. 

Combining your earlier suggestion with a minor modification, how about this:
> Unless it is not overridden by AIMD window increase, CUBIC is very careful in this region. The convex profile aims that the window increases very slowly at the beginning when the cwnd is around W_max and gradually increases its increase rate.

**Comment by lisongxu** [comment]
Hi Yoshi, Finally I see the confusion. Thank you!

Hi Vidhi, "Unless it is not overridden by AIMD window increase, CUBIC is very careful in this region" should be "Unless it is overridden by AIMD window increase, CUBIC is very careful in this region"? Thank you!

**Comment by nsdyoshi** [comment]
Hi Vidhi,
Thanks for the updates. I think we will need to update it as Lisong suggested, but other than that, it works for me.
Thanks for pointing out, Lisong!

**Comment by goelvidhi** [comment]
Thanks. Fixed it in #76
